### ISSUE TITLE
Browse Error (Also system resource usage too high 1.3G usage on 3G ram PC :D)

### ISSUE THREAD

**Issue by toprak** [manami-project/manami#325]
_Before posting: Please check if you have the newest version. If there is a newer version please check if the problem still occurs with the newest version._

**Manami version:**
3.10.12
**operating system + version**:
Arch Linux, its up to date system so yeah.
**JDK/JRE + version:**
```openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9)
OpenJDK 64-Bit Server VM (build 20.0.1+9, mixed mode)```
**Steps to reproduce:**
do ctrl+1 in homepage and find some anime then click the blue colored name and get this error
**What is the current behavior:**
it gives that error ```java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:381)
	at java.desktop/java.awt.Desktop.browse(Desktop.java:531)
	at io.github.manamiproject.manami.gui.extensions.EventTargetExtensionsKt.hyperlink$lambda$1$lambda$0(EventTargetExtensions.kt:33)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3599)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3903)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1887)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2620)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:1623)```
	
	here is the terminal output ```[tbb@hai ~]$ java -jar manami.jar 
[0.005s][warning][cds] A jar file is not the one used while building the shared archive file: /usr/lib/jvm/java-20-openjdk/lib/modules
[0.006s][warning][cds] /usr/lib/jvm/java-20-openjdk/lib/modules timestamp has changed.
11:48:43.350 [main] INFO io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - Successfully added [anilist.co] to RetryBehaviorRegistry
11:48:43.566 [Network-Dispatcher-1] INFO io.github.manamiproject.modb.core.httpclient.UserAgents - Initializing user-agents for [FIREFOX (DESKTOP)]
11:48:43.568 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for user-agent file [modb-firefox-desktop-user-agents.txt] in classpath.
11:48:43.573 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for property [modb.httpclient.useragents.firefox.desktop.path]
11:48:43.574 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - None of the above could be found. Falling back to hard coded user agents.
11:48:43.574 [Network-Dispatcher-1] INFO io.github.manamiproject.modb.core.httpclient.UserAgents - Initializing user-agents for [FIREFOX (MOBILE)]
11:48:43.574 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for user-agent file [modb-firefox-mobile-user-agents.txt] in classpath.
11:48:43.575 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for property [modb.httpclient.useragents.firefox.mobile.path]
11:48:43.575 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - None of the above could be found. Falling back to hard coded user agents.
11:48:43.575 [Network-Dispatcher-1] INFO io.github.manamiproject.modb.core.httpclient.UserAgents - Initializing user-agents for [CHROME (DESKTOP)]
11:48:43.575 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for user-agent file [modb-chrome-desktop-user-agents.txt] in classpath.
11:48:43.576 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for property [modb.httpclient.useragents.chrome.desktop.path]
11:48:43.576 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - None of the above could be found. Falling back to hard coded user agents.
11:48:43.576 [Network-Dispatcher-1] INFO io.github.manamiproject.modb.core.httpclient.UserAgents - Initializing user-agents for [CHROME (MOBILE)]
11:48:43.576 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for user-agent file [modb-chrome-mobile-user-agents.txt] in classpath.
11:48:43.577 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for property [modb.httpclient.useragents.chrome.mobile.path]
11:48:43.577 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - None of the above could be found. Falling back to hard coded user agents.
11:48:46.624 [main] INFO io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - Successfully added [anime-planet.com] to RetryBehaviorRegistry
11:48:46.661 [main] INFO io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - Successfully added [kitsu.io] to RetryBehaviorRegistry
11:48:46.664 [main] WARN io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - RetryBehaviorConfig named [kitsu.io] already exists in repository
11:48:46.666 [main] WARN io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - RetryBehaviorConfig named [kitsu.io] already exists in repository
11:48:46.683 [main] INFO io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - Successfully added [myanimelist.net] to RetryBehaviorRegistry
11:48:48.172 [main] INFO io.github.manamiproject.manami.app.Manami$Companion - Starting manami
11:48:48.465 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.versioning.DefaultLatestVersionChecker$Companion - Checking if there is a new version available.
Apr 30, 2023 11:48:48 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @41a90fa8'
11:48:49.506 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.AnimeCachePopulator$Companion - Populating cache with anime from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/anime-offline-database-minified.json].
11:48:49.674 [CPU-Dispatcher-2] INFO io.github.manamiproject.modb.dbparser.DatabaseFileParser$Companion - Downloading database file from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/anime-offline-database-minified.json]
Apr 30, 2023 11:48:53 AM tornadofx.Stylesheet$Companion detectAndInstallUrlHandler
INFO: Installing CSS url handler, since it was not picked up automatically
11:48:54.019 [CPU-Dispatcher-3] INFO io.github.manamiproject.modb.dbparser.AnimeDatabaseJsonStringParser$Companion - Parsing database
11:49:12.258 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.AnimeCachePopulator$Companion - Finished populating cache with anime from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/anime-offline-database-minified.json].
11:49:13.584 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Populating cache with dead entries from [anidb.net]
11:49:13.666 [CPU-Dispatcher-4] INFO io.github.manamiproject.modb.dbparser.DatabaseFileParser$Companion - Downloading database file from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/dead-entries/anidb.json]
11:49:14.175 [CPU-Dispatcher-1] INFO io.github.manamiproject.modb.dbparser.DeadEntriesJsonStringParser$Companion - Parsing dead entries
11:49:14.465 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Finished populating cache with dead entries from [anidb.net]
11:49:14.466 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Populating cache with dead entries from [anilist.co]
11:49:14.466 [CPU-Dispatcher-2] INFO io.github.manamiproject.modb.dbparser.DatabaseFileParser$Companion - Downloading database file from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/dead-entries/anilist.json]
11:49:14.872 [CPU-Dispatcher-3] INFO io.github.manamiproject.modb.dbparser.DeadEntriesJsonStringParser$Companion - Parsing dead entries
11:49:18.073 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Finished populating cache with dead entries from [anilist.co]
11:49:18.074 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Populating cache with dead entries from [kitsu.io]
11:49:18.075 [CPU-Dispatcher-4] INFO io.github.manamiproject.modb.dbparser.DatabaseFileParser$Companion - Downloading database file from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/dead-entries/kitsu.json]
11:49:18.327 [CPU-Dispatcher-1] INFO io.github.manamiproject.modb.dbparser.DeadEntriesJsonStringParser$Companion - Parsing dead entries
11:49:18.477 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Finished populating cache with dead entries from [kitsu.io]
11:49:18.477 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Populating cache with dead entries from [myanimelist.net]
11:49:18.478 [CPU-Dispatcher-2] INFO io.github.manamiproject.modb.dbparser.DatabaseFileParser$Companion - Downloading database file from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/dead-entries/myanimelist.json]
11:49:18.735 [CPU-Dispatcher-3] INFO io.github.manamiproject.modb.dbparser.DeadEntriesJsonStringParser$Companion - Parsing dead entries
11:49:18.942 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Finished populating cache with dead entries from [myanimelist.net]
Apr 30, 2023 11:50:38 AM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.label' in stylesheet jar:file:/home/tbb/manami.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Apr 30, 2023 11:50:38 AM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.label' in stylesheet jar:file:/home/tbb/manami.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Apr 30, 2023 11:50:38 AM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.label' in stylesheet jar:file:/home/tbb/manami.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Apr 30, 2023 11:50:38 AM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '*.label' in stylesheet jar:file:/home/tbb/manami.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
Apr 30, 2023 11:50:38 AM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in unnamed module of loader 'app')' while converting value for '-fx-background-color' from rule '*.list-view' in stylesheet jar:file:/home/tbb/manami.jar!/com/sun/javafx/scene/control/skin/modena/modena.bss
11:52:39.634 [tornadofx-thread-1] INFO io.github.manamiproject.manami.app.Manami$Companion - Terminating manami
Killed
[tbb@hai ~]$ java -jar manami.jar 
[0.536s][warning][cds] A jar file is not the one used while building the shared archive file: /usr/lib/jvm/java-20-openjdk/lib/modules
[0.536s][warning][cds] /usr/lib/jvm/java-20-openjdk/lib/modules timestamp has changed.
11:55:02.963 [main] INFO io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - Successfully added [anilist.co] to RetryBehaviorRegistry
11:55:03.033 [Network-Dispatcher-1] INFO io.github.manamiproject.modb.core.httpclient.UserAgents - Initializing user-agents for [FIREFOX (DESKTOP)]
11:55:03.035 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for user-agent file [modb-firefox-desktop-user-agents.txt] in classpath.
11:55:03.037 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for property [modb.httpclient.useragents.firefox.desktop.path]
11:55:03.042 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - None of the above could be found. Falling back to hard coded user agents.
11:55:03.042 [Network-Dispatcher-1] INFO io.github.manamiproject.modb.core.httpclient.UserAgents - Initializing user-agents for [FIREFOX (MOBILE)]
11:55:03.042 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for user-agent file [modb-firefox-mobile-user-agents.txt] in classpath.
11:55:03.042 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for property [modb.httpclient.useragents.firefox.mobile.path]
11:55:03.043 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - None of the above could be found. Falling back to hard coded user agents.
11:55:03.043 [Network-Dispatcher-1] INFO io.github.manamiproject.modb.core.httpclient.UserAgents - Initializing user-agents for [CHROME (DESKTOP)]
11:55:03.043 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for user-agent file [modb-chrome-desktop-user-agents.txt] in classpath.
11:55:03.043 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for property [modb.httpclient.useragents.chrome.desktop.path]
11:55:03.044 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - None of the above could be found. Falling back to hard coded user agents.
11:55:03.044 [Network-Dispatcher-1] INFO io.github.manamiproject.modb.core.httpclient.UserAgents - Initializing user-agents for [CHROME (MOBILE)]
11:55:03.044 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for user-agent file [modb-chrome-mobile-user-agents.txt] in classpath.
11:55:03.045 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - Checking for property [modb.httpclient.useragents.chrome.mobile.path]
11:55:03.045 [Network-Dispatcher-1] DEBUG io.github.manamiproject.modb.core.httpclient.UserAgents - None of the above could be found. Falling back to hard coded user agents.
11:55:04.618 [main] INFO io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - Successfully added [anime-planet.com] to RetryBehaviorRegistry
11:55:04.653 [main] INFO io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - Successfully added [kitsu.io] to RetryBehaviorRegistry
11:55:04.656 [main] WARN io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - RetryBehaviorConfig named [kitsu.io] already exists in repository
11:55:04.657 [main] WARN io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - RetryBehaviorConfig named [kitsu.io] already exists in repository
11:55:04.666 [main] INFO io.github.manamiproject.modb.core.httpclient.retry.RetryableRegistry - Successfully added [myanimelist.net] to RetryBehaviorRegistry
11:55:06.035 [main] INFO io.github.manamiproject.manami.app.Manami$Companion - Starting manami
11:55:06.254 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.versioning.DefaultLatestVersionChecker$Companion - Checking if there is a new version available.
Apr 30, 2023 11:55:06 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @41a90fa8'
11:55:07.214 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.AnimeCachePopulator$Companion - Populating cache with anime from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/anime-offline-database-minified.json].
11:55:07.218 [CPU-Dispatcher-2] INFO io.github.manamiproject.modb.dbparser.DatabaseFileParser$Companion - Downloading database file from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/anime-offline-database-minified.json]
11:55:09.166 [CPU-Dispatcher-3] INFO io.github.manamiproject.modb.dbparser.AnimeDatabaseJsonStringParser$Companion - Parsing database
Apr 30, 2023 11:55:10 AM tornadofx.Stylesheet$Companion detectAndInstallUrlHandler
INFO: Installing CSS url handler, since it was not picked up automatically
11:55:17.998 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.AnimeCachePopulator$Companion - Finished populating cache with anime from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/anime-offline-database-minified.json].
11:55:18.006 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Populating cache with dead entries from [anidb.net]
11:55:18.009 [CPU-Dispatcher-4] INFO io.github.manamiproject.modb.dbparser.DatabaseFileParser$Companion - Downloading database file from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/dead-entries/anidb.json]
11:55:18.212 [CPU-Dispatcher-1] INFO io.github.manamiproject.modb.dbparser.DeadEntriesJsonStringParser$Companion - Parsing dead entries
11:55:18.301 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Finished populating cache with dead entries from [anidb.net]
11:55:18.302 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Populating cache with dead entries from [anilist.co]
11:55:18.302 [CPU-Dispatcher-2] INFO io.github.manamiproject.modb.dbparser.DatabaseFileParser$Companion - Downloading database file from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/dead-entries/anilist.json]
11:55:18.637 [CPU-Dispatcher-3] INFO io.github.manamiproject.modb.dbparser.DeadEntriesJsonStringParser$Companion - Parsing dead entries
11:55:19.236 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Finished populating cache with dead entries from [anilist.co]
11:55:19.237 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Populating cache with dead entries from [kitsu.io]
11:55:19.237 [CPU-Dispatcher-4] INFO io.github.manamiproject.modb.dbparser.DatabaseFileParser$Companion - Downloading database file from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/dead-entries/kitsu.json]
11:55:19.479 [CPU-Dispatcher-1] INFO io.github.manamiproject.modb.dbparser.DeadEntriesJsonStringParser$Companion - Parsing dead entries
11:55:19.571 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Finished populating cache with dead entries from [kitsu.io]
11:55:19.571 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Populating cache with dead entries from [myanimelist.net]
11:55:19.572 [CPU-Dispatcher-2] INFO io.github.manamiproject.modb.dbparser.DatabaseFileParser$Companion - Downloading database file from [https://raw.githubusercontent.com/manami-project/anime-offline-database/master/dead-entries/myanimelist.json]
11:55:19.805 [CPU-Dispatcher-3] INFO io.github.manamiproject.modb.dbparser.DeadEntriesJsonStringParser$Companion - Parsing dead entries
11:55:19.893 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.populator.DeadEntriesCachePopulator$Companion - Finished populating cache with dead entries from [myanimelist.net]
11:55:28.923 [pool-3-thread-1] INFO io.github.manamiproject.manami.app.cache.DefaultAnimeCache$Companion - No cache hit for [https://myanimelist.net/anime/41361/Eiga_Daisuki_Pompo-san]
11:55:28.925 [pool-3-thread-1] DEBUG io.github.manamiproject.manami.app.cache.loader.SimpleCacheLoader$Companion - Loading anime from [https://myanimelist.net/anime/41361/Eiga_Daisuki_Pompo-san]
11:55:28.927 [pool-3-thread-1] DEBUG io.github.manamiproject.modb.mal.MalDownloader$Companion - Downloading [malId=41361/Eiga_Daisuki_Pompo-san]
11:55:30.101 [pool-3-thread-1] WARN io.github.manamiproject.manami.app.cache.DefaultAnimeCache$Companion - Not populating cache with key [https://myanimelist.net/anime/41361], because it already exists
Apr 30, 2023 11:55:49 AM tornadofx.DefaultErrorHandler uncaughtException
SEVERE: Uncaught error
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:381)
	at java.desktop/java.awt.Desktop.browse(Desktop.java:531)
	at io.github.manamiproject.manami.gui.extensions.EventTargetExtensionsKt.hyperlink$lambda$1$lambda$0(EventTargetExtensions.kt:33)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3599)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3903)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1887)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2620)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:1623)```
**What is the expected behavior:**
just work i guess

**Comment by toprak** [comment]
also I wish there were option add episode number to track which ep I am on

**Comment by manami-project** [comment]
Hey @toprak,
thank you for reporting that.
Which window manager do you use? KDE, Gnome, ....

**Comment by toprak** [comment]
@manami-project icewm
